### ISSUE TITLE
boot jar, 生成jar无法启动

### ISSUE THREAD

**Issue by AmbitionLover** [livk-cloud/spring-boot-extension#56]
org.springframework.boot.loader.JarLauncher 缺少@org.springframework.boot.autoconfigure.SpringBtApplication注解

<img width="1423" alt="image" src="https://github.com/livk-cloud/spring-boot-extension/assets/46626203/5fef4b89-194d-4209-9a61-0f3a41787b58">

使用 SpringApplication.run(SpringApplication.class, args);

<img width="1273" alt="image" src="https://github.com/livk-cloud/spring-boot-extension/assets/46626203/9530ba8e-4d35-48f3-9800-d19d0dbbb3af">

**Comment by livk-cloud** [comment]
启动类上需要添加@org.springframework.boot.autoconfigure.SpringBootApplication注解
![image](https://github.com/livk-cloud/spring-boot-extension/assets/50291874/d0226473-4179-41b0-97aa-358765a7e1ad)

**Comment by livk-cloud** [comment]
感谢提交issue，SpringBoot打包之后是fat jar，调用链上的最后一个类是org.springframework.boot.loader.Launcher

**Comment by livk-cloud** [comment]
已修复[commit](https://github.com/livk-cloud/spring-boot-extension/commit/6146f45e201656516859aeeaa0b09ed2fd16f8c5)
